name: 'Install_package'

on:
  pull_request:
  push:

jobs:

  uv-install:

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - run: uv sync
