name: 'Install_package'

on:
  pull_request:
  push:

jobs:

  pre-commit:

    runs-on: ubuntu-22.04
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
